(ns hooks.cg.ts-macros
  "clj-kondo hook for cg.ts-macros/define-all-ts-fns.

   cg.geo is one call to that macro plus a few hand-written helpers. The macro
   reads src/cg/ts_registry.cljc at compile time and mints about 1450
   defns, one per in-scope registry entry, plus the promoted receiver ops and
   the hero-verb aliases. None of those names exist for static analysis, so
   without this hook every call into the minted surface reads as `Unresolved
   var`, and the one call the expansion makes back into itself
   (buffer-params -> buffer-parameters-create, at the bottom of cg.geo) reads
   as `Unresolved symbol`.

   The names are data in hooks.cg.ts-names, generated by `bb ts:kondo`,
   because a hook runs in SCI and cannot read the registry file. Regenerate
   that data with the registry snapshot; `bb ts:sync` does both.

   net.willcohen/native exports the same node-building logic as
   hooks.native.generated. This hook keeps its own copy of the few lines it
   needs, so that a consumer of this config does not have to import a second
   one to make it load."
  (:require [hooks.cg.ts-names :as names]
            [clj-kondo.hooks-api :as api]))

(defn- defn-node
  "Build a defn node for one minted name.

   `arities` is a vector of argument vectors. An arity the hook omits reads as
   a false invalid-arity at every call site. The bodies are dropped, because
   they hold dispatcher calls on quoted metadata maps, which say nothing a call
   site needs.

   Each arity gets an EMPTY body, not a nil one. clj-kondo types a nil body as
   the return type, and then every numeric use of a minted accessor reads as
   `Expected: number, received: nil` -- (double (geo/x pt)) and (geo/area g) in
   the tests, for example. An empty body leaves the return type unknown."
  [fn-name arities]
  (api/list-node
   (list* (api/token-node 'defn)
          (api/token-node fn-name)
          (for [args arities]
            (api/list-node
             (list (api/vector-node (mapv api/token-node args))))))))

(defn define-all-ts-fns
  "Expand the macro call into a `do` of one defn per minted name."
  [_]
  {:node (api/list-node
          (cons (api/token-node 'do)
                (for [[fn-name arities] names/minted]
                  (defn-node fn-name arities))))})
