;; Auto-generated by `bb gen:signatures`. Do not edit by hand.
;; Source: enriched register-operation! calls beside each op's defn.
;; To change an op contract, edit its register-operation! + regenerate.
(ns cg.dsl.signatures-generated)

(def built-ins
  '{"block-presence"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "spec", :type :any, :role nil, :optional false}],
  :outputs [{:name "summary", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "block-presence"},
 "category-crosstab"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "spec", :type :any, :role nil, :optional false}],
  :outputs [{:name "crosstab", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "category-crosstab"},
 "ds/->dataset"
 {:inputs [{:name "data", :type :any, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/->dataset"},
 "ds/block-presence"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "spec", :type :any, :role nil, :optional false}],
  :outputs [{:name "summary", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/block-presence"},
 "ds/category-crosstab"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "spec", :type :any, :role nil, :optional false}],
  :outputs [{:name "crosstab", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/category-crosstab"},
 "ds/column-names"
 {:inputs
  [{:name "dataset", :type :dataset, :role nil, :optional false}],
  :outputs [{:name "names", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/column-names"},
 "ds/concat"
 {:inputs
  [{:name "datasets", :type :any, :role nil, :optional false}
   {:name "more", :type :any, :role nil, :optional true}],
  :outputs [{:name "dataset", :type :dataset}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/concat"},
 "ds/filter-by-column"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "column", :type :keyword, :role nil, :optional false}
   {:name "predicate", :type :keyword, :role nil, :optional false}
   {:name "value", :type :any, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/filter-by-column"},
 "ds/geojson->dataset"
 {:inputs
  [{:name "geojson", :type :string, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/geojson->dataset"},
 "ds/has-column?"
 {:inputs
  [{:name "dataset", :type :dataset, :role nil, :optional false}
   {:name "column", :type :keyword, :role nil, :optional false}],
  :outputs [{:name "present?", :type :boolean}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/has-column?"},
 "ds/load-gdal"
 {:inputs
  [{:name "source", :type :string, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :source,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/load-gdal"},
 "ds/load-geojson"
 {:inputs [{:name "path", :type :string, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :source,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/load-geojson"},
 "ds/load-shapefile"
 {:inputs [{:name "path", :type :string, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :source,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/load-shapefile"},
 "ds/map-layer"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "opts", :type :any, :role nil, :optional true}],
  :outputs [{:name "layer", :type :any}],
  :flags #{},
  :kind :sink,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/map-layer"},
 "ds/report-table"
 {:inputs
  [{:name "summary", :type :any, :role :row, :optional false}
   {:name "opts", :type :any, :role nil, :optional true}],
  :outputs [{:name "table", :type :any}],
  :flags #{},
  :kind :sink,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/report-table"},
 "ds/row-count"
 {:inputs
  [{:name "dataset", :type :dataset, :role nil, :optional false}],
  :outputs [{:name "count", :type :number}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/row-count"},
 "ds/rows"
 {:inputs
  [{:name "dataset", :type :dataset, :role nil, :optional false}
   {:name "shape", :type :keyword, :role nil, :optional true}],
  :outputs [{:name "rows", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{},
  :source :built-in,
  :location nil,
  :qualified-name "ds/rows"},
 "ds/summarize"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "spec", :type :any, :role nil, :optional false}],
  :outputs [{:name "summary", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/summarize"},
 "ds/transform-crs"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "target-crs", :type :string, :role nil, :optional false}
   {:name "source-crs", :type :string, :role nil, :optional true}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{:idempotent},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/transform-crs"},
 "ds/write-csv"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "path", :type :string, :role nil, :optional false}],
  :outputs [{:name "ok", :type :any}],
  :flags #{},
  :kind :sink,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/write-csv"},
 "ds/write-geojson"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "path", :type :string, :role nil, :optional false}],
  :outputs [{:name "ok", :type :any}],
  :flags #{},
  :kind :sink,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "ds/write-geojson"},
 "filter"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "column", :type :keyword, :role nil, :optional false}
   {:name "predicate", :type :keyword, :role nil, :optional false}
   {:name "value", :type :any, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :dataset}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "filter"},
 "group-by"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "column", :type :keyword, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :groups}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "group-by"},
 "into"
 {:inputs
  [{:name "groups", :type :any, :role :row, :optional false}
   {:name "target", :type :any, :role nil, :optional false}],
  :outputs [{:name "result", :type :any, :level :map}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "into"},
 "map"
 {:inputs
  [{:name "groups", :type :any, :role :row, :optional false}
   {:name "component", :type :any, :role nil, :optional false}],
  :outputs [{:name "result", :type :any, :level :groups}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "map"},
 "map-layer"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "opts", :type :any, :role nil, :optional true}],
  :outputs [{:name "layer", :type :any}],
  :flags #{},
  :kind :sink,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "map-layer"},
 "partition-by"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "column", :type :keyword, :role nil, :optional false}],
  :outputs [{:name "dataset", :type :dataset, :level :groups}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "partition-by"},
 "report-table"
 {:inputs
  [{:name "summary", :type :any, :role :row, :optional false}
   {:name "opts", :type :any, :role nil, :optional true}],
  :outputs [{:name "table", :type :any}],
  :flags #{},
  :kind :sink,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "report-table"},
 "summarize"
 {:inputs
  [{:name "dataset", :type :dataset, :role :row, :optional false}
   {:name "spec", :type :any, :role nil, :optional false}],
  :outputs [{:name "summary", :type :any}],
  :flags #{},
  :kind :transformer,
  :threading-modes #{:table},
  :source :built-in,
  :location nil,
  :qualified-name "summarize"}})
