(ns gen-kondo-hook
  "JVM-only generator: snapshots the names and arities that
   cg.ts-macros/define-all-ts-fns mints into
   resources/clj-kondo.exports/net.willcohen/cg/hooks/cg/ts_names.clj.

   A clj-kondo hook runs in SCI with no file access, so it cannot read
   src/cg/ts_registry.cljc the way the macro does. The minted surface is
   copied here as data instead, the same way net.willcohen/proj keeps a copy of
   its fn-defs beside its hook.

   The copy holds names and arities only, not the bodies. That is all the hook
   needs: one defn node per name, one arity per argument vector.

   Run via `bb ts:kondo`. `bb ts:sync` runs it too, because the snapshot and
   the registry must agree.

   Mirrors the `bb gen:signatures` pattern (auto-gen header + quoted data
   literal in a generated ns)."
  (:require [clojure.pprint :as pp]
            [clojure.string :as str]))

(set! *warn-on-reflection* true)

(def generated-path
  "resources/clj-kondo.exports/net.willcohen/cg/hooks/cg/ts_names.clj")

(defn arity-vectors
  "Return the argument vectors of one emitted defn form, for both the
   single-arity shape (defn nm [args] body) and the multi-arity shape
   (defn nm ([args] body) ...). A docstring or an attribute map before the
   first arity is skipped."
  [form]
  (let [body (drop 2 form)
        body (if (string? (first body)) (rest body) body)
        body (if (map? (first body)) (rest body) body)]
    (if (vector? (first body))
      [(first body)]
      (mapv first body))))

(defn placeholder-args
  "Rename one argument vector to positional placeholders. The hook gives every
   generated defn a nil body, so a name that reads as a binding makes
   :unused-binding fire at each call site. The leading underscore stops that.
   A variadic tail keeps its position."
  [args]
  (let [n (atom -1)]
    (mapv (fn [a]
            (if (= '& a)
              '&
              (symbol (str "_a" (swap! n inc)))))
          args)))

(defn build-minted
  "Load the registry, expand it the way the macro does, and return a sorted map
   of public name -> vector of placeholder argument vectors.

   A name the expansion emits more than once keeps the LAST set of arities.
   That is what the expanded `do` produces at run time, where the last defn
   wins, so modelling it any other way would let clj-kondo accept a call the
   run time rejects. 76 of the 1527 emitted defns collide this way today, 27 of
   them with a different arity set."
  []
  (require 'cg.ts-macros)
  (let [load-registry (resolve 'cg.ts-macros/load-registry)
        emit-all      (resolve 'cg.ts-macros/emit-all)
        forms         (emit-all (load-registry)
                                {:receiver-call 'dispatch-receiver-call
                                 :static-call   'dispatch-static-call
                                 :ctor          'dispatch-ctor})]
    (into (sorted-map)
          (for [form forms
                :when (= 'clojure.core/defn (first form))]
            [(second form) (mapv placeholder-args (arity-vectors form))]))))

(defn emit-str
  [minted]
  (str ";; Auto-generated by `bb ts:kondo`. Do not edit by hand.\n"
       ";; Source: src/cg/ts_registry.cljc, through cg.ts-macros/emit-all.\n"
       ";;\n"
       ";; A clj-kondo hook cannot read a file, so the surface that\n"
       ";; (define-all-ts-fns) mints is copied here as data.\n"
       "(ns hooks.cg.ts-names)\n\n"
       "(def minted\n"
       "  \"Public name -> the argument vectors of each arity. A name that the\n"
       "   expansion emits more than once keeps the last set of arities, because\n"
       "   the last defn in the expanded `do` wins.\"\n"
       "  '"
       (str/trimr (with-out-str (pp/pprint minted)))
       ")\n"))

(defn -main [& _]
  (let [minted (build-minted)]
    (spit generated-path (emit-str minted))
    (println "Wrote" generated-path "with" (count minted) "minted names.")))
