(ns gen-signatures
  "JVM-only generator: snapshots cg.feature/operation-registry into
   src/cg/dsl/signatures_generated.cljc — the pure-data `built-ins` map
   the eval-free browser parser imports.

   The single source of truth is the enriched `register-operation!` call
   beside each op's defn. The parser cannot execute heavy-ns code
   (tech.ml.dataset / JTS / wasmts), so this snapshot is how the op
   contract reaches the squint-compiled parser. Run via `bb gen:signatures`.

   Mirrors the `bb ts:sync` pattern (auto-gen header + quoted data literal
   in a generated ns)."
  (:require [clojure.string :as str]
            [clojure.pprint :as pp]))

(set! *warn-on-reflection* true)

(def runtime-nses
  "Namespaces whose load triggers the register-operation! calls. Loading
   them on JVM is fine; the parser never loads them."
  '[cg.feature cg.dataset cg.dataset.agg cg.geo cg.run cg.macros])

(def generated-path "src/cg/dsl/signatures_generated.cljc")

(defn project-entry
  "Project one operation-registry entry into zero or more
   [dsl-spelling signature-map] pairs — one per :dsl-name plus each
   :dsl-aliases entry. Returns nil when the entry carries no :dsl-name
   (i.e. it is not parser-facing; internal step-factories fall out here).

   The signature-map matches cg.dsl.signatures' built-ins shape exactly
   (the keys produced by sig/input/output), so the generated map is a
   drop-in for the hand-written one."
  [entry]
  (when-let [dsl-name (:dsl-name entry)]
    (let [base {:inputs (mapv (fn [i] {:name (:name i)
                                       :type (:type i)
                                       :role (:role i)
                                       :optional (boolean (:optional i))})
                              (:inputs entry))
                :outputs (mapv (fn [o] (cond-> {:name (:name o) :type (:type o)}
                                         (contains? o :level) (assoc :level (:level o))))
                               (:outputs entry))
                :flags (or (:flags entry) #{})
                :kind (:kind entry)
                :threading-modes (or (:threading-modes entry) #{})
                :source :built-in
                :location nil}]
      (mapv (fn [s] [s (assoc base :qualified-name s)])
            (cons dsl-name (:dsl-aliases entry))))))

(defn build-built-ins
  "Require the runtime nses (so register-operation! / register-group! have
   run), then project every parser-facing entry into the {spelling ->
   signature} map, key-sorted for stable diffs. Pure data, no fn calls.

   Both registries are scanned: operations (register-operation!) and groups
   (register-group!, e.g. transform-crs). A group is parser-facing the same
   way an operation is — by carrying a :dsl-name parser slice; its
   :expansion-fn is ignored by project-entry."
  []
  (doseq [n runtime-nses] (require n))
  (let [ops    ((resolve 'cg.feature/all-operations))
        groups ((resolve 'cg.feature/all-groups))]
    (into (sorted-map)
          (mapcat project-entry)
          (concat (vals ops) (vals groups)))))

(defn emit-str
  [built-ins]
  (str ";; Auto-generated by `bb gen:signatures`. Do not edit by hand.\n"
       ";; Source: enriched register-operation! calls beside each op's defn.\n"
       ";; To change an op contract, edit its register-operation! + regenerate.\n"
       "(ns cg.dsl.signatures-generated)\n\n"
       "(def built-ins\n  '"
       (str/trimr (with-out-str (pp/pprint built-ins)))
       ")\n"))

(defn -main [& _]
  (let [built-ins (build-built-ins)
        content (emit-str built-ins)]
    (spit generated-path content)
    (println "Wrote" generated-path "with" (count built-ins) "parser-facing op entries.")))
